### ISSUE TITLE
BOFT runs out of memory on 8GB

### ISSUE THREAD

**Issue by rockerBOO** [KohakuBlueleaf/LyCORIS#148] opened 2024-02-05 17:18 UTC
Thank you for adding BOFT. Running into this using using Kohya-ss using BOFT. On commit f03434907cf717596edc0f0d8a396e10ac5eb4b6

```
network_dim=10
network_alpha=16
network_train_unet_only=true
sdpa=true
mixed_precision="fp16"
network_module = "lycoris.kohya"
network_args = [ 
  "algo=boft",
  "constrain=1e-5",
  "dropout=0.5",
  "module_dropout=0.1",
]
```

```
Enable SDPA for U-Net
import network module: lycoris.kohya
network args: ['algo=boft', 'constrain=1e-5', 'dropout=0.5', 'module_dropout=0.1']
net_kwargs {'algo': 'boft', 'constrain': '1e-5', 'dropout': '0.5', 'module_dropout': '0.1'}
2024-02-05 12:07:27|[LyCORIS]-INFO: Using rank adaptation algo: boft
2024-02-05 12:07:27|[LyCORIS]-INFO: Use Dropout value: 0.5
2024-02-05 12:07:27|[LyCORIS]-INFO: Create LyCORIS Module
2024-02-05 12:07:27|[LyCORIS]-INFO: Use BOFT(7, 3) (equivalent to factor=6) for dim=768 and factor=10
2024-02-05 12:07:27|[LyCORIS]-INFO: Use BOFT(9, 3) (equivalent to factor=6) for dim=3072 and factor=10
2024-02-05 12:07:27|[LyCORIS]-INFO: create LyCORIS for Text Encoder: 72 modules.
2024-02-05 12:07:27|[LyCORIS]-INFO: Create LyCORIS Module
2024-02-05 12:07:27|[LyCORIS]-INFO: Use BOFT(5, 5) (equivalent to factor=10) for dim=320 and factor=10
2024-02-05 12:07:27|[LyCORIS]-INFO: Use BOFT(7, 5) (equivalent to factor=10) for dim=1280 and factor=10
2024-02-05 12:07:27|[LyCORIS]-INFO: Use BOFT(8, 5) (equivalent to factor=10) for dim=2560 and factor=10
2024-02-05 12:07:27|[LyCORIS]-INFO: Use BOFT(6, 5) (equivalent to factor=10) for dim=640 and factor=10
2024-02-05 12:07:27|[LyCORIS]-INFO: Use BOFT(9, 5) (equivalent to factor=10) for dim=5120 and factor=10
2024-02-05 12:07:27|[LyCORIS]-INFO: Use BOFT(10, 5) (equivalent to factor=10) for dim=10240 and factor=10
2024-02-05 12:07:27|[LyCORIS]-INFO: Use BOFT(0, 2) (equivalent to factor=4) for dim=4 and factor=10
2024-02-05 12:07:27|[LyCORIS]-INFO: create LyCORIS for U-Net: 282 modules.
2024-02-05 12:07:27|[LyCORIS]-INFO: module type table: {'ButterflyOFTModule': 354}
2024-02-05 12:07:27|[LyCORIS]-INFO: enable LyCORIS for U-Net
```

I tried to go to as low of a dim as possible to get it to run. Swapping `algo=boft` with `algo=diag-oft` runs the training without running out of memory.

Traceback with `network_train_unet_only=true` 

```
Traceback (most recent call last):
  File "/mnt/900/builds/sd-scripts/train_network.py", line 1117, in <module>
    trainer.train(args)
  File "/mnt/900/builds/sd-scripts/train_network.py", line 867, in train
    loss = self.process_batch(batch, is_train, tokenizers, text_encoders, unet, vae, noise_scheduler, vae_dtype, weight_dtype, accelerator, args, train_text_encoder=train_text_encoder)
  File "/mnt/900/builds/sd-scripts/train_network.py", line 132, in process_batch
    noise_pred = self.call_unet(
  File "/mnt/900/builds/sd-scripts/train_network.py", line 82, in call_unet
    noise_pred = unet(noisy_latents, timesteps, text_conds).sample
  File "/mnt/900/builds/sd-scripts/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/900/builds/sd-scripts/.venv/lib/python3.10/site-packages/accelerate/utils/operations.py", line 680, in forward
    return model_forward(*args, **kwargs)
  File "/mnt/900/builds/sd-scripts/.venv/lib/python3.10/site-packages/accelerate/utils/operations.py", line 668, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/mnt/900/builds/sd-scripts/.venv/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/mnt/900/builds/sd-scripts/library/original_unet.py", line 1900, in forward
    sample = self.mid_block(sample, emb, encoder_hidden_states=encoder_hidden_states)
  File "/mnt/900/builds/sd-scripts/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/900/builds/sd-scripts/library/original_unet.py", line 1400, in forward
    hidden_states = attn(hidden_states, encoder_hidden_states).sample
  File "/mnt/900/builds/sd-scripts/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/900/builds/sd-scripts/library/original_unet.py", line 1228, in forward
    hidden_states = block(hidden_states, context=encoder_hidden_states, timestep=timestep)
  File "/mnt/900/builds/sd-scripts/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/900/builds/sd-scripts/library/original_unet.py", line 1157, in forward
    hidden_states = self.ff(self.norm3(hidden_states)) + hidden_states
  File "/mnt/900/builds/sd-scripts/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/900/builds/sd-scripts/library/original_unet.py", line 1102, in forward
    hidden_states = module(hidden_states)
  File "/mnt/900/builds/sd-scripts/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/900/builds/sd-scripts/library/original_unet.py", line 1080, in forward
    hidden_states, gate = self.proj(hidden_states).chunk(2, dim=-1)
  File "/mnt/900/builds/sd-scripts/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/900/builds/sd-scripts/LyCORIS/lycoris/modules/boft.py", line 198, in forward
    w = self.make_weight(scale, x.device)
  File "/mnt/900/builds/sd-scripts/LyCORIS/lycoris/modules/boft.py", line 174, in make_weight
    inp = rearrange(inp, "(c k g) ... -> (c g k) ...", g=2, k=2**i * r_b)
  File "/mnt/900/builds/sd-scripts/.venv/lib/python3.10/site-packages/einops/einops.py", line 483, in rearrange
    return reduce(cast(Tensor, tensor), pattern, reduction='rearrange', **axes_lengths)
  File "/mnt/900/builds/sd-scripts/.venv/lib/python3.10/site-packages/einops/einops.py", line 412, in reduce
    return _apply_recipe(recipe, tensor, reduction_type=reduction)
  File "/mnt/900/builds/sd-scripts/.venv/lib/python3.10/site-packages/einops/einops.py", line 241, in _apply_recipe
    return backend.reshape(tensor, final_shapes)
  File "/mnt/900/builds/sd-scripts/.venv/lib/python3.10/site-packages/einops/_backends.py", line 84, in reshape
    return x.reshape(shape)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 26.00 MiB (GPU 0; 7.62 GiB total capacity; 7.08 GiB already allocated; 71.75 MiB free; 7.27 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_spli
```

I have also gotten it to run out of memory on this line https://github.com/KohakuBlueleaf/LyCORIS/blob/f03434907cf717596edc0f0d8a396e10ac5eb4b6/lycoris/modules/boft.py#L145

Thank you. No rush on a fix but wanted to report.

**Comment by KohakuBlueleaf** [comment] 2024-02-05 17:21
BOFT will cost more vram so I think it could be a expected behaviour

I will make "max m" mechanism so you can use less vram (but also less information though, for now I force user to use max m to get full matrix)

**Comment by KohakuBlueleaf** [comment] 2024-02-05 17:23
Can you try to use fp8_base and preset=attn (which should not OOM) and report the final vram usage difference between oft and boft?

**Comment by KohakuBlueleaf** [comment] 2024-02-06 01:42
> Hmm what do you mean by fp8_base? I'm on a 2080 so no fp8 support. Also tried preset=attn in network_args but says it couldn't find that preset? Is there something else I need to get that preset? Using the sd-scripts version of kohya which doesn't have presets i believe.
> 
> ```
> import network module: lycoris.kohya
> network args: ['algo=boft', 'constrain=1e-5', 'dropout=0.5', 'module_dropout=0.1', 'preset=attn']
> net_kwargs {'algo': 'boft', 'constrain': '1e-5', 'dropout': '0.5', 'module_dropout': '0.1', 'preset': 'attn'}
> Error: cannot read preset file.  [Errno 2] No such file or directory: 'attn'
> Traceback (most recent call last):
>   File "/mnt/900/builds/sd-scripts/train_network.py", line 1117, in <module>
>     trainer.train(args)
>   File "/mnt/900/builds/sd-scripts/train_network.py", line 382, in train
>     network = network_module.create_network(
>   File "/mnt/900/builds/sd-scripts/LyCORIS/lycoris/kohya/__init__.py", line 88, in create_network
>     assert preset is not None
> AssertionError
> ```
> 
> I was able to get it running by using gradient_checkpointing (and also running full_fp16 but not sure if that was required).
> 
> 5472MB VRAM with BOFT with gradient_checkpointing and full_fp16
> 
> ```
> network args: ['algo=boft', 'constrain=1e-5', 'dropout=0.5', 'module_dropout=0.1']
> net_kwargs {'algo': 'boft', 'constrain': '1e-5', 'dropout': '0.5', 'module_dropout': '0.1'}
> 2024-02-05 13:52:41|[LyCORIS]-INFO: Using rank adaptation algo: boft
> 2024-02-05 13:52:41|[LyCORIS]-INFO: Use Dropout value: 0.5
> 2024-02-05 13:52:41|[LyCORIS]-INFO: Create LyCORIS Module
> 2024-02-05 13:52:41|[LyCORIS]-INFO: Use BOFT(7, 3) (equivalent to factor=6) for dim=768 and factor=10
> 2024-02-05 13:52:41|[LyCORIS]-INFO: Use BOFT(9, 3) (equivalent to factor=6) for dim=3072 and factor=10
> 2024-02-05 13:52:41|[LyCORIS]-INFO: create LyCORIS for Text Encoder: 72 modules.
> 2024-02-05 13:52:41|[LyCORIS]-INFO: Create LyCORIS Module
> 2024-02-05 13:52:41|[LyCORIS]-INFO: Use BOFT(5, 5) (equivalent to factor=10) for dim=320 and factor=10
> 2024-02-05 13:52:41|[LyCORIS]-INFO: Use BOFT(7, 5) (equivalent to factor=10) for dim=1280 and factor=10
> 2024-02-05 13:52:41|[LyCORIS]-INFO: Use BOFT(8, 5) (equivalent to factor=10) for dim=2560 and factor=10
> 2024-02-05 13:52:41|[LyCORIS]-INFO: Use BOFT(6, 5) (equivalent to factor=10) for dim=640 and factor=10
> 2024-02-05 13:52:41|[LyCORIS]-INFO: Use BOFT(9, 5) (equivalent to factor=10) for dim=5120 and factor=10
> 2024-02-05 13:52:41|[LyCORIS]-INFO: Use BOFT(10, 5) (equivalent to factor=10) for dim=10240 and factor=10
> 2024-02-05 13:52:41|[LyCORIS]-INFO: Use BOFT(0, 2) (equivalent to factor=4) for dim=4 and factor=10
> 2024-02-05 13:52:41|[LyCORIS]-INFO: create LyCORIS for U-Net: 282 modules.
> 2024-02-05 13:52:41|[LyCORIS]-INFO: module type table: {'ButterflyOFTModule': 354}
> 2024-02-05 13:52:41|[LyCORIS]-INFO: enable LyCORIS for text encoder
> 2024-02-05 13:52:41|[LyCORIS]-INFO: enable LyCORIS for U-Net
> ```
> 
> 3730MB with OFT with a "dim" of 4 (using the same gradient_checkpointing and full_fp16)
> 
> ```
> network args: ['algo=diag-oft', 'constrain=1e-5', 'dropout=0.5', 'module_dropout=0.1']
> net_kwargs {'algo': 'diag-oft', 'constrain': '1e-5', 'dropout': '0.5', 'module_dropout': '0.1'}
> 2024-02-05 13:57:02|[LyCORIS]-INFO: Using rank adaptation algo: diag-oft
> 2024-02-05 13:57:02|[LyCORIS]-INFO: Use Dropout value: 0.5
> 2024-02-05 13:57:02|[LyCORIS]-INFO: Create LyCORIS Module
> 2024-02-05 13:57:02|[LyCORIS]-INFO: create LyCORIS for Text Encoder: 72 modules.
> 2024-02-05 13:57:02|[LyCORIS]-INFO: Create LyCORIS Module
> 2024-02-05 13:57:02|[LyCORIS]-INFO: create LyCORIS for U-Net: 282 modules.
> 2024-02-05 13:57:02|[LyCORIS]-INFO: module type table: {'DiagOFTModule': 354}
> 2024-02-05 13:57:02|[LyCORIS]-INFO: enable LyCORIS for text encoder
> 2024-02-05 13:57:02|[LyCORIS]-INFO: enable LyCORIS for U-Net
> ```
> 
> additionally using `runwayml/stable-diffusion-1-5` using resolution 640 images (in buckets) for context

Just use latest dev of sd-scripts and add --fp8_base
Once your card support amp you can use it

**Comment by KohakuBlueleaf** [comment] 2024-02-06 01:44
Oh and it should be preset=attn-only

Checked your log and the difference is expected

I can consider to make some custom backward just like what I did in loha

**Comment by rockerBOO** [comment] 2024-02-06 02:45
`preset=attn-only` 7000MB roughly (gradient_checkpointing=false, no fp8_base). 
Tried with fp8_base and it was going over (maybe 7160MB before it stopped). Runs more near the edge of the limit with like xorg running on the GPU too. 

3674MB - fp8_base=true + gradient_checkpointing=true, preset=attn-only
2970MB - fp8_base=false + gradient_checkpointing=true, preset=attn-only

Thanks for the help, should be able to try it some more. Thank you.

**Comment by KohakuBlueleaf** [comment] 2024-02-06 11:10
I will close this issue since it looks like the behaviour is expected.
Further optimizations and more options will be investigated.

**Closed by KohakuBlueleaf** 2024-02-06 11:10 UTC
