### ISSUE TITLE
extract_lycon error

### ISSUE THREAD

**Issue by rugia813** [KohakuBlueleaf/LyCORIS#71] opened 2023-07-20 15:13 UTC
hi, 
I had been using the extract_lycon scripts for a while with no problem.
Recently, I started to getting the following error:

```
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
Traceback (most recent call last):
  File "D:\AI Arts\LyCORIS\tools\extract_locon.py", line 129, in <module>
    main()
  File "D:\AI Arts\LyCORIS\tools\extract_locon.py", line 98, in main
    db = load_models_from_stable_diffusion_checkpoint(args.is_v2, args.db_model)
  File "D:\AI Arts\LyCORIS\lycoris\kohya_model_utils.py", line 901, in load_models_from_stable_diffusion_checkpoint
    info = text_model.load_state_dict(converted_text_encoder_checkpoint)
  File "C:\Users\rugia\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CLIPTextModel:
        Missing key(s) in state_dict: "text_model.embeddings.position_ids".
```

the cmd:
```
python ./tools/extract_locon.py --safetensors --device=cuda --mode="fixed" --linear_dim=64 --conv_dim=32 "xxx/v1-5-pruned-emaonly.ckpt" "input.ckpt" "output.safetensors"
```
I am not familiar with python, and I have already spent a whole day trying figure out what went wrong to no avail... :(
Does anyone know what could cause this?
Thanks

**Comment by rugia813** [comment] 2023-07-20 15:39
Thanks!!!

**Comment by wshaf97** [comment] 2023-07-23 00:50
I just started getting this exact error as well. Was working 2-3 days ago and will not output a convert now with that error. I appreciate looking into it quickly!

**Comment by KohakuBlueleaf** [comment] 2023-07-25 08:26
Bad news
The problem may in kohya's utils

I will suggest you guys to check if the diffusers' version is too new

**Comment by wshaf97** [comment] 2023-07-25 15:37
Do you know why it would have stopped working unexpectedly if the script was not updated? As in the global diffusers version could have been updated and caused it to break? Are you able to investigate requirements or reproduce the issue?

**Comment by KohakuBlueleaf** [comment] 2023-07-25 16:34
> Do you know why it would have stopped working unexpectedly if the script was not updated? As in the global diffusers version could have been updated and caused it to break? Are you able to investigate requirements or reproduce the issue?

It took me few hours on trying to reproduce this issue
And the thing is, I cannot reproduce it.

I will try more but I cannot resolve this within few days I guess

**Comment by rugia813** [comment] 2023-07-27 09:14
I have found that the script actually works on my older fine-tuned models, 
it only throws the error for models trained in the last few weeks or so.

To my understanding, the issue is that models usually have this property `text_model.embeddings.position_ids`,
but for some reason, models fine-tuned using dreambooth in the last few weeks do not have it, 
and this causes the error when the script tried to load it.

I have no idea what does position ids do, but I figured I'd try just add empty data to the same property name to bypass the error. it actually worked, and the result looked alright. but this is definitely not a proper fix.

**Comment by KohakuBlueleaf** [comment] 2023-07-27 09:23
@rugia813 Yes
The position_ids should be in the models
May I ask which tool you use to train the dreambooth model?
Kohya or diffusers' example?

**Comment by KohakuBlueleaf** [comment] 2023-07-27 09:24
If you use kohya_ss' sd scripts to train the dreambooth model can failed to use extract_lycon

Can you try to use your dreambooth model in any kohya's utils and see if it work?
As I know, the loading method in kohya doesn't allow missing keys

**Comment by KohakuBlueleaf** [comment] 2023-07-27 09:38
@rugia813 @wshaf97 
I have updated to 1.8.2 which use new utils system in kohya-ss
Please check if that work for you

**Comment by rugia813** [comment] 2023-07-27 09:57
> @rugia813 Yes The position_ids should be in the models May I ask which tool you use to train the dreambooth model? Kohya or diffusers' example?

I use Shivam Shrirao's dreambooth colab.
I'll try new version
thank you

**Comment by rugia813** [comment] 2023-07-27 10:12
unfortunately, 1.8.2 still gives the same error :(

**Comment by KohakuBlueleaf** [comment] 2023-07-27 10:50
@rugia813 unfortunately
This means all kohya series things can't support your model :(

I will try to figure out if it is possible to make a utils to add the position_ids we need

Your model is sd2 arch?

**Comment by rugia813** [comment] 2023-07-27 12:23
> @rugia813 unfortunately This means all kohya series things can't support your model :(
> 
> I will try to figure out if it is possible to make a utils to add the position_ids we need
> 
understood, thanks for your help.

> Your model is sd2 arch?
mine was trained on 1.5 base

**Comment by wshaf97** [comment] 2023-07-27 16:36
@rugia813 would you be able to provide an example as to how you got it working by modifying position ids and I can do some testing when I get home/this weekend?

**Comment by rugia813** [comment] 2023-07-28 01:41
@wshaf97 sure
https://github.com/rugia813/LyCORIS/commit/3f86ee2241d6c1286183394c325c8a73b2946fe1

**Comment by wshaf97** [comment] 2023-07-28 02:48
@rugia813 This resolves the issue for the time being! Thank you for the fix! 
@KohakuBlueleaf I can test any revisions or updates if you continue to work on resolving the bug.

**Comment by KohakuBlueleaf** [comment] 2023-07-28 02:51
@wshaf97 thx!
I will try to make a utils to add position ids
Just found that kohya have that for sd2 but not sd1

**Comment by KohakuBlueleaf** [comment] 2023-07-30 09:59
@wshaf97 @rugia813 
Can you try to use latest transformers?
It looks like the transformers version for LyCORIS and your training script are different

**Comment by KohakuBlueleaf** [comment] 2023-07-30 09:59
I met this problem but "unexpected" when using latest transformers
I guess if you use latest one
You can use the model without position ids

**Comment by rugia813** [comment] 2023-08-01 03:36
well, it is kinda funny.
now that it does not require position_ids, so the custom model should load, yes.
but it is throwing the error `Unexpected key(s) in state_dict: "text_model.embeddings.position_ids"` when loading the base sd 1.5 model...
so it is still not working, for the opposite reason.
maybe this issue will be resolved in future version of transformers?

just curious, do you know what does the position_ids do, and does it play a role in model fine-tuning or inference?

**Comment by KohakuBlueleaf** [comment] 2023-08-01 03:37
> well, it is kinda funny. now that it does not require position_ids, so the custom model should load, yes. but it is throwing the error `Unexpected key(s) in state_dict: "text_model.embeddings.position_ids"` when loading the base sd 1.5 model... so it is still not working, for the opposite reason. maybe this issue will be resolved in future version of transformers?
> 
> just curious, do you know what does the position_ids do, and does it play a role in model fine-tuning or inference?

Yes
Basically different version error
Base1.5 from old
Your from new

And it successfully bugged

**Comment by KohakuBlueleaf** [comment] 2023-08-01 03:38
> well, it is kinda funny. now that it does not require position_ids, so the custom model should load, yes. but it is throwing the error `Unexpected key(s) in state_dict: "text_model.embeddings.position_ids"` when loading the base sd 1.5 model... so it is still not working, for the opposite reason. maybe this issue will be resolved in future version of transformers?
> 
> just curious, do you know what does the position_ids do, and does it play a role in model fine-tuning or inference?

position_ids just a torch.arange
Originally implement as buffer so it appeared in states_dict

**Comment by ryenots** [comment] 2023-08-21 10:51
Just had this error myself, using the latest versions of all requirements except for ```diffusers-0.10.2```. Was there a fix discovered in this thread? I'm having a hard time deciphering all this.

**Comment by KohakuBlueleaf** [comment] 2023-08-21 15:43
> Just had this error myself, using the latest versions of all requirements except for `diffusers-0.10.2`. Was there a fix discovered in this thread? I'm having a hard time deciphering all this.

If you get "unexpected key"
I will suggest you to install older version of diffusers (maybe 1.17)

If you get "missing key"
You will need to add the missed position_ids back into your model file manually

I will try to got a method to automatically fix this problem

**Comment by ryenots** [comment] 2023-08-22 06:33
I am getting ```Unexpected key(s) in state_dict: "text_model.embeddings.position_ids".``` With diffusers versions 0.10.2, 0.17.0, and 0.20.0 (latest) I get the same error.

**Comment by KohakuBlueleaf** [comment] 2023-08-22 06:37
> I am getting `Unexpected key(s) in state_dict: "text_model.embeddings.position_ids".` With diffusers versions 0.10.2, 0.17.0, and 0.20.0 (latest) I get the same error. Not sure how to proceed.

You should not get this error before 0.19.0
Are you sure that us "unexpected" but not "missing"?

**Comment by KohakuBlueleaf** [comment] 2023-09-27 13:41
Already comfirmed this error is caused by the mismatch of the model version and transformers version
Since for CLIP models there is no restriction on "highest" version of transformers, it is possible to solve this problem with requirements.txt or something like that.

Will close this issue.

**Closed by KohakuBlueleaf** 2023-09-27 13:41 UTC
