### ISSUE TITLE
0.1.7 Traceback when using  scale weight norm

### ISSUE THREAD

**Issue by bmaltais** [KohakuBlueleaf/LyCORIS#60] opened 2023-06-27 23:29 UTC
When trying to train under 0.1.7 with scale weight norm and network dropout under SD15 and SD2.1 `--network_module=lycoris.kohya --network_args "conv_dim=16" "conv_alpha=8" "use_cp=True" "algo=loha"`
                         
I get:

```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\kohya_ss\train_network.py:873 in <module>                                                     │
│                                                                                                  │
│   870 │   args = parser.parse_args()                                                             │
│   871 │   args = train_util.read_config_from_file(args, parser)                                  │
│   872 │                                                                                          │
│ ❱ 873 │   train(args)                                                                            │
│   874                                                                                            │
│                                                                                                  │
│ D:\kohya_ss\train_network.py:693 in train                                                        │
│                                                                                                  │
│   690 │   │   │   │   optimizer.zero_grad(set_to_none=True)                                      │
│   691 │   │   │                                                                                  │
│   692 │   │   │   if args.scale_weight_norms:                                                    │
│ ❱ 693 │   │   │   │   keys_scaled, mean_norm, maximum_norm = network.apply_max_norm_regulariza   │
│   694 │   │   │   │   │   args.scale_weight_norms, accelerator.device                            │
│   695 │   │   │   │   )                                                                          │
│   696 │   │   │   │   max_mean_logs = {"Keys Scaled": keys_scaled, "Average key norm": mean_no   │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\lycoris\kohya.py:378 in apply_max_norm_regularization         │
│                                                                                                  │
│   375 │   │   │   if hasattr(lora, 'apply_max_norm'):                                            │
│   376 │   │   │   │   scaled, norm = lora.apply_max_norm(max_norm_value, device)                 │
│   377 │   │   │   │   norms.append(norm)                                                         │
│ ❱ 378 │   │   │   │   scaled += int(scaled)                                                      │
│   379 │   │                                                                                      │
│   380 │   │   for lora in self.text_encoder_loras:                                               │
│   381 │   │   │   if hasattr(lora, 'apply_max_norm'):                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: result type Long can't be cast to the desired output type Bool
```

Turning off scale weight norm result in no traceback.

**Comment by KohakuBlueleaf** [comment] 2023-06-28 12:51
ok it is 1.7.1 now

**Comment by bmaltais** [comment] 2023-06-28 15:50
The new version appear to have solved the issue!

**Comment by KohakuBlueleaf** [comment] 2023-06-28 16:21
good!
I will close this issue few days after if it is resolved

**Comment by bmaltais** [comment] 2023-06-28 17:22
@KohakuBlueleaf One thing I find strange is that training a LoHA with SD2.1 does not produce any good results... but using the same parameters on 1.5 produce amazing results. Not sure why... but I tought I would let you know in case there is something in the code that can be adapted to better suit SD2.1 training.

Kohya has added `Scale v prediction loss` to his code and it made a huge difference for SD2.1 training results. I wonder if that parameter is used under the lycoris network?

**Comment by KohakuBlueleaf** [comment] 2023-06-28 17:25
Lycoris will not affect any training loop related things
Include what you mentioned
So you actually need to ask kohya
"Will you disable that things when receiving 3rd party network module"

BTW i think the answer is that doesn't affect

**Comment by KohakuBlueleaf** [comment] 2023-06-28 17:27
Ok
Will fix jt

**Comment by bmaltais** [comment] 2023-06-28 17:27
I will test the other ones also... just in case

**Comment by bmaltais** [comment] 2023-06-28 17:34
iA3 still work fine. Actually produce pretty good results in my test.

**Comment by bmaltais** [comment] 2023-06-28 18:08
@KohakuBlueleaf I tried creating a DYlora... mind you, it is the 1st time I try so it is possible this issue is not related to 1.7.1... but just in case. Here is the command I ran:

`accelerate launch --num_cpu_threads_per_process=2 "train_network.py" --enable_bucket --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5"
                         --train_data_dir="D:/dataset/Buster Keaton/img_g5" --resolution="768,768" --output_dir="D:/lycoris/sd15" --logging_dir="D:\dataset\Buster Keaton/lora2/logs"
                         --network_alpha="16" --training_comment="trigger words: BstrKtn" --save_model_as=safetensors --network_module=lycoris.kohya --network_args "conv_dim=16" "conv_alpha=8"        
                         "use_cp=True" "block_size=1" "algo=dylora" --text_encoder_lr=1.0 --unet_lr=1.0 --network_dim=32 --gradient_accumulation_steps=2 --output_name="Buster Keaton-3.0a-dyl-sd15"    
                         --lr_scheduler_num_cycles="2" --scale_weight_norms="1" --network_dropout="0.1" --learning_rate="1.0" --lr_scheduler="cosine" --train_batch_size="5" --max_train_steps="112"    
                         --save_every_n_epochs="1" --mixed_precision="bf16" --save_precision="fp16" --seed="1234" --caption_extension=".txt-no" --cache_latents --cache_latents_to_disk
                         --optimizer_type="Prodigy" --max_data_loader_n_workers="0" --bucket_reso_steps=1 --min_snr_gamma=10 --xformers --bucket_no_upscale --multires_noise_iterations="8"
                         --multires_noise_discount="0.2" --wandb_api_key="False"`
                         
 Here is the error I got:
 
 ```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\kohya_ss\train_network.py:873 in <module>                                                     │
│                                                                                                  │
│   870 │   args = parser.parse_args()                                                             │
│   871 │   args = train_util.read_config_from_file(args, parser)                                  │
│   872 │                                                                                          │
│ ❱ 873 │   train(args)                                                                            │
│   874                                                                                            │
│                                                                                                  │
│ D:\kohya_ss\train_network.py:693 in train                                                        │
│                                                                                                  │
│   690 │   │   │   │   optimizer.zero_grad(set_to_none=True)                                      │
│   691 │   │   │                                                                                  │
│   692 │   │   │   if args.scale_weight_norms:                                                    │
│ ❱ 693 │   │   │   │   keys_scaled, mean_norm, maximum_norm = network.apply_max_norm_regulariza   │
│   694 │   │   │   │   │   args.scale_weight_norms, accelerator.device                            │
│   695 │   │   │   │   )                                                                          │
│   696 │   │   │   │   max_mean_logs = {"Keys Scaled": keys_scaled, "Average key norm": mean_no   │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\lycoris\kohya.py:386 in apply_max_norm_regularization         │
│                                                                                                  │
│   383 │   │   │   │   norms.append(norm)                                                         │
│   384 │   │   │   │   scaled += int(scaled)                                                      │
│   385 │   │                                                                                      │
│ ❱ 386 │   │   return scaled, sum(norms)/len(norms), max(norms)                                   │
│   387                                                                                            │
│   388                                                                                            │
│   389 class IA3Network(torch.nn.Module):                                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ZeroDivisionError: division by zero
steps:   0%|

**Comment by bmaltais** [comment] 2023-06-28 18:42
Looking at the code it does appear to be related to the norms getting divided by a 0 value... so probably related to 1.7.1

**Comment by KohakuBlueleaf** [comment] 2023-06-29 04:41
> Looking at the code it does appear to be related to the norms getting divided by a 0 value... so probably related to 1.7.1

I fix the bug in the lokr and disable scale weight norm for dylora
dylora didn't support scale weight norm yet (and didn't support grad acc)

I will need to rewrite my implementation of dylora first, so dylora didn't support lot of things
already push a usable version to 1.7.2

**Comment by bmaltais** [comment] 2023-06-29 11:08
Tested the latest 1.7.2 release woth LoKr ang got this after a few steps of training:

```
─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\kohya_ss\train_network.py:873 in <module>                                                     │
│                                                                                                  │
│   870 │   args = parser.parse_args()                                                             │
│   871 │   args = train_util.read_config_from_file(args, parser)                                  │
│   872 │                                                                                          │
│ ❱ 873 │   train(args)                                                                            │
│   874                                                                                            │
│                                                                                                  │
│ D:\kohya_ss\train_network.py:693 in train                                                        │
│                                                                                                  │
│   690 │   │   │   │   optimizer.zero_grad(set_to_none=True)                                      │
│   691 │   │   │                                                                                  │
│   692 │   │   │   if args.scale_weight_norms:                                                    │
│ ❱ 693 │   │   │   │   keys_scaled, mean_norm, maximum_norm = network.apply_max_norm_regulariza   │
│   694 │   │   │   │   │   args.scale_weight_norms, accelerator.device                            │
│   695 │   │   │   │   )                                                                          │
│   696 │   │   │   │   max_mean_logs = {"Keys Scaled": keys_scaled, "Average key norm": mean_no   │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\lycoris\kohya.py:380 in apply_max_norm_regularization         │
│                                                                                                  │
│   377 │   │                                                                                      │
│   378 │   │   for lora in self.unet_loras:                                                       │
│   379 │   │   │   if hasattr(lora, 'apply_max_norm'):                                            │
│ ❱ 380 │   │   │   │   scaled, norm = lora.apply_max_norm(max_norm_value, device)                 │
│   381 │   │   │   │   norms.append(norm)                                                         │
│   382 │   │   │   │   scaled += int(scaled)                                                      │
│   383                                                                                            │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\torch\utils\_contextlib.py:115 in decorate_context            │
│                                                                                                  │
│   112 │   @functools.wraps(func)                                                                 │
│   113 │   def decorate_context(*args, **kwargs):                                                 │
│   114 │   │   with ctx_factory():                                                                │
│ ❱ 115 │   │   │   return func(*args, **kwargs)                                                   │
│   116 │                                                                                          │
│   117 │   return decorate_context                                                                │
│   118                                                                                            │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\lycoris\lokr.py:233 in apply_max_norm                         │
│                                                                                                  │
│   230 │   │   if scaled:                                                                         │
│   231 │   │   │   modules = (4 - self.use_w1 - self.use_w2 + (not self.use_w2 and self.cp))      │
│   232 │   │   │   if self.use_w1:                                                                │
│ ❱ 233 │   │   │   │   self.lokr_w1_a *= ratio**(1/modules)                                       │
│   234 │   │   │   │   self.lokr_w1_b *= ratio**(1/modules)                                       │
│   235 │   │   │   else:                                                                          │
│   236 │   │   │   │   self.lokr_w1 *= ratio**(1/modules)                                         │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1614 in __getattr__                │
│                                                                                                  │
│   1611 │   │   │   modules = self.__dict__['_modules']                                           │
│   1612 │   │   │   if name in modules:                                                           │
│   1613 │   │   │   │   return modules[name]                                                      │
│ ❱ 1614 │   │   raise AttributeError("'{}' object has no attribute '{}'".format(                  │
│   1615 │   │   │   type(self).__name__, name))                                                   │
│   1616 │                                                                                         │
│   1617 │   def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'LokrModule' object has no attribute 'lokr_w1_a'
```

**Comment by KohakuBlueleaf** [comment] 2023-06-30 13:58
> Tested the latest 1.7.2 release woth LoKr ang got this after a few steps of training:
> 
> ```
> ─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
> │ D:\kohya_ss\train_network.py:873 in <module>                                                     │
> │                                                                                                  │
> │   870 │   args = parser.parse_args()                                                             │
> │   871 │   args = train_util.read_config_from_file(args, parser)                                  │
> │   872 │                                                                                          │
> │ ❱ 873 │   train(args)                                                                            │
> │   874                                                                                            │
> │                                                                                                  │
> │ D:\kohya_ss\train_network.py:693 in train                                                        │
> │                                                                                                  │
> │   690 │   │   │   │   optimizer.zero_grad(set_to_none=True)                                      │
> │   691 │   │   │                                                                                  │
> │   692 │   │   │   if args.scale_weight_norms:                                                    │
> │ ❱ 693 │   │   │   │   keys_scaled, mean_norm, maximum_norm = network.apply_max_norm_regulariza   │
> │   694 │   │   │   │   │   args.scale_weight_norms, accelerator.device                            │
> │   695 │   │   │   │   )                                                                          │
> │   696 │   │   │   │   max_mean_logs = {"Keys Scaled": keys_scaled, "Average key norm": mean_no   │
> │                                                                                                  │
> │ D:\kohya_ss\venv\lib\site-packages\lycoris\kohya.py:380 in apply_max_norm_regularization         │
> │                                                                                                  │
> │   377 │   │                                                                                      │
> │   378 │   │   for lora in self.unet_loras:                                                       │
> │   379 │   │   │   if hasattr(lora, 'apply_max_norm'):                                            │
> │ ❱ 380 │   │   │   │   scaled, norm = lora.apply_max_norm(max_norm_value, device)                 │
> │   381 │   │   │   │   norms.append(norm)                                                         │
> │   382 │   │   │   │   scaled += int(scaled)                                                      │
> │   383                                                                                            │
> │                                                                                                  │
> │ D:\kohya_ss\venv\lib\site-packages\torch\utils\_contextlib.py:115 in decorate_context            │
> │                                                                                                  │
> │   112 │   @functools.wraps(func)                                                                 │
> │   113 │   def decorate_context(*args, **kwargs):                                                 │
> │   114 │   │   with ctx_factory():                                                                │
> │ ❱ 115 │   │   │   return func(*args, **kwargs)                                                   │
> │   116 │                                                                                          │
> │   117 │   return decorate_context                                                                │
> │   118                                                                                            │
> │                                                                                                  │
> │ D:\kohya_ss\venv\lib\site-packages\lycoris\lokr.py:233 in apply_max_norm                         │
> │                                                                                                  │
> │   230 │   │   if scaled:                                                                         │
> │   231 │   │   │   modules = (4 - self.use_w1 - self.use_w2 + (not self.use_w2 and self.cp))      │
> │   232 │   │   │   if self.use_w1:                                                                │
> │ ❱ 233 │   │   │   │   self.lokr_w1_a *= ratio**(1/modules)                                       │
> │   234 │   │   │   │   self.lokr_w1_b *= ratio**(1/modules)                                       │
> │   235 │   │   │   else:                                                                          │
> │   236 │   │   │   │   self.lokr_w1 *= ratio**(1/modules)                                         │
> │                                                                                                  │
> │ D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1614 in __getattr__                │
> │                                                                                                  │
> │   1611 │   │   │   modules = self.__dict__['_modules']                                           │
> │   1612 │   │   │   if name in modules:                                                           │
> │   1613 │   │   │   │   return modules[name]                                                      │
> │ ❱ 1614 │   │   raise AttributeError("'{}' object has no attribute '{}'".format(                  │
> │   1615 │   │   │   type(self).__name__, name))                                                   │
> │   1616 │                                                                                         │
> │   1617 │   def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:             │
> ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
> AttributeError: 'LokrModule' object has no attribute 'lokr_w1_a'
> ```

@bmaltais This problem should be resolved with 1.8.0.dev2

**Comment by bmaltais** [comment] 2023-06-30 23:02
I will test it once I am back and let you know how it goes .

**Comment by bmaltais** [comment] 2023-07-01 00:46
Hummm... I get this error when I try the new version:

```
Traceback (most recent call last):
  File "D:\kohya_ss\venv\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\kohya_ss\lora_gui.py", line 729, in train_model
    import lycoris
  File "D:\kohya_ss\venv\lib\site-packages\lycoris\__init__.py", line 1, in <module>
    from lycoris import (
ImportError: cannot import name 'modules' from partially initialized module 'lycoris' (most likely due to a circular import) (D:\kohya_ss\venv\lib\site-packages\lycoris\__init__.py)
```

I checked with pip freeze and the module is installed properly...

**Comment by bmaltais** [comment] 2023-07-01 01:04
I am getting this error after installing the latest version:

```
Traceback (most recent call last):
  File "D:\kohya_ss\venv\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\kohya_ss\lora_gui.py", line 729, in train_model
    import lycoris
  File "D:\kohya_ss\venv\lib\site-packages\lycoris\__init__.py", line 1, in <module>
    from lycoris import (
ImportError: cannot import name 'modules' from partially initialized module 'lycoris' (most likely due to a circular import) (D:\kohya_ss\venv\lib\site-packages\lycoris\__init__.py)
```

If I revert back to 1.7.2 it goes away.

**Comment by KohakuBlueleaf** [comment] 2023-07-01 04:15
@bmaltais this error os very weird
More like something wrong in your environment
I will check your repo

**Comment by KohakuBlueleaf** [comment] 2023-07-01 08:07
I don't know if this problem is caused by pacakge without __init__.py
I added it into 1.8.0.dev3
plz check it

**Comment by bmaltais** [comment] 2023-07-01 11:19
Not sure what is going on. I tried deleting the venv and re-install, no change. The new version still produce the error... bu uninstalling and installing 1.7.2 fix the issue... stumped...

**Comment by bmaltais** [comment] 2023-07-01 11:23
When I install the 1.7.2 version the content of the venv/lib folder look like this:

![image](https://github.com/KohakuBlueleaf/LyCORIS/assets/7474674/b7ea9c8c-03a5-4ff7-af22-dab80dd7394f)

and this is what it look like under 1.8.2.dev3:

![image](https://github.com/KohakuBlueleaf/LyCORIS/assets/7474674/03fc7d42-0af3-4ccc-b0d9-9d387ac12a77)

**Comment by KohakuBlueleaf** [comment] 2023-07-01 11:59
> When I install the 1.7.2 version the content of the venv/lib folder look like this:
> 
> ![image](https://user-images.githubusercontent.com/7474674/250271285-2fa89008-b82a-4946-9cd7-1c842546ba23.png)
> 
> and this is what it look like under 1.8.2.dev3:
> 
> ![image](https://user-images.githubusercontent.com/7474674/250271311-f58437f6-56d8-4802-8b3e-f9f4b4f2354c.png)

This is what it should be
I upload a dev4 plz check it

and can you try to use source code?
in my environment which is also using kohya-ss/sd-script
1.8.0.dev2 just working normally for all algo it have

**Comment by KohakuBlueleaf** [comment] 2023-07-01 12:34
@bmaltais ok I got the reason
s_dist is a trap here

**Comment by KohakuBlueleaf** [comment] 2023-07-01 12:36
@bmaltais I upload the 1.8.0.dev5 which should resolve this problem
the s_dist ignore the submodule so you get that error

**Comment by bmaltais** [comment] 2023-07-01 13:02
@KohakuBlueleaf That fixed the module install issue. It is giving me this error when trying to train a lokr. I have not tried other types :

```
Create LyCORIS Module
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\kohya_ss\train_network.py:984 in <module>                                                     │
│                                                                                                  │
│   981 │   args = train_util.read_config_from_file(args, parser)                                  │
│   982 │                                                                                          │
│   983 │   trainer = NetworkTrainer()                                                             │
│ ❱ 984 │   trainer.train(args)                                                                    │
│   985                                                                                            │
│                                                                                                  │
│ D:\kohya_ss\train_network.py:270 in train                                                        │
│                                                                                                  │
│   267 │   │   │   network, _ = network_module.create_network_from_weights(1, args.network_weig   │
│   268 │   │   else:                                                                              │
│   269 │   │   │   # LyCORIS will work with this...                                               │
│ ❱ 270 │   │   │   network = network_module.create_network(                                       │
│   271 │   │   │   │   1.0,                                                                       │
│   272 │   │   │   │   args.network_dim,                                                          │
│   273 │   │   │   │   args.network_alpha,                                                        │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\lycoris\kohya\__init__.py:68 in create_network                │
│                                                                                                  │
│    65 │   │   │   multiplier = multiplier,                                                       │
│    66 │   │   )                                                                                  │
│    67 │   else:                                                                                  │
│ ❱  68 │   │   network = LycorisNetwork(                                                          │
│    69 │   │   │   text_encoder, unet,                                                            │
│    70 │   │   │   multiplier=multiplier,                                                         │
│    71 │   │   │   lora_dim=network_dim, conv_lora_dim=conv_dim,                                  │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\lycoris\kohya\__init__.py:236 in __init__                     │
│                                                                                                  │
│   233 │   │                                                                                      │
│   234 │   │   self.text_encoder_loras = []                                                       │
│   235 │   │   for i, te in enumerate(text_encoders):                                             │
│ ❱ 236 │   │   │   self.text_encoder_loras.extend(create_modules(                                 │
│   237 │   │   │   │   LycorisNetwork.LORA_PREFIX_TEXT_ENCODER + (f'{i+1}' if use_index else ''   │
│   238 │   │   │   │   te,                                                                        │
│   239 │   │   │   │   LycorisNetwork.TEXT_ENCODER_TARGET_REPLACE_MODULE                          │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\lycoris\kohya\__init__.py:152 in create_modules               │
│                                                                                                  │
│   149 │   │   │   │   │   │   lora_name = prefix + '.' + name + '.' + child_name                 │
│   150 │   │   │   │   │   │   lora_name = lora_name.replace('.', '_')                            │
│   151 │   │   │   │   │   │   if child_module.__class__.__name__ == 'Linear' and lora_dim>0:     │
│ ❱ 152 │   │   │   │   │   │   │   lora = network_module(                                         │
│   153 │   │   │   │   │   │   │   │   lora_name, child_module, self.multiplier,                  │
│   154 │   │   │   │   │   │   │   │   self.lora_dim, self.alpha,                                 │
│   155 │   │   │   │   │   │   │   │   self.dropout, self.rank_dropout, self.module_dropout,      │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\lycoris\modules\lokr.py:193 in __init__                       │
│                                                                                                  │
│   190 │   │                                                                                      │
│   191 │   │   self.multiplier = multiplier                                                       │
│   192 │   │   self.org_module = [org_module]                                                     │
│ ❱ 193 │   │   weight = make_kron(                                                                │
│   194 │   │   │   self.org_module[0].weight.data,                                                │
│   195 │   │   │   self.lokr_w1 if self.use_w1 else self.lokr_w1_a@self.lokr_w1_b,                │
│   196 │   │   │   (self.lokr_w2 if self.use_w2                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: make_kron() takes 3 positional arguments but 4 were given
```

**Comment by KohakuBlueleaf** [comment] 2023-07-01 13:35
@bmaltais updated dev6

**Comment by bmaltais** [comment] 2023-07-01 13:44
So far so good. I am not sure if the key norm does much on LoKr... the results are really strange... but this is a LoKr so I don't know what type of behavious to expect...

The key norm graph is not at all what I am used to see...

![image](https://github.com/KohakuBlueleaf/LyCORIS/assets/7474674/d186f031-3365-4743-a78c-5c73fa24e78c)

**Comment by KohakuBlueleaf** [comment] 2023-07-01 13:49
@bmaltais I think that's because lokr use few parameters to learn high rank data
So 1 parameter actually get gradient from lot outputs
Basically it has higher "effective batch size"

So it is more stable and more possible to get lowrr norm(overfit)

**Comment by bmaltais** [comment] 2023-07-01 14:26
@KohakuBlueleaf The effect is certainly visible and beneficial. Here is a test I did with the following prompt:

`alice in wonderland style, dog on a bench, girl in the street`

LoKr no norm from 1.7.2:

![00080-938539292-alice in wonderland style, dog on a bench, girl in the street_](https://github.com/KohakuBlueleaf/LyCORIS/assets/7474674/185d1ef2-4834-485c-8425-02ab63bdddeb)

LoKr norm 1 from 1.8.0:

![00079-938539292-alice in wonderland style, dog on a bench, girl in the street_](https://github.com/KohakuBlueleaf/LyCORIS/assets/7474674/9537ab6f-fa2b-4eca-9ad8-d3c8ae96548a)

The output from the 1.8.0 LyCORIS LoKr is following the prompt and source style much better. Example of dataset imeges:

![1book21-200x300-0000--](https://github.com/KohakuBlueleaf/LyCORIS/assets/7474674/e6d609a0-afa4-43cc-8e07-1a7c9aabf84d)

**Comment by KohakuBlueleaf** [comment] 2023-07-01 14:28
@bmaltais cool
so I think I can close this issue?

**Comment by bmaltais** [comment] 2023-07-01 14:28
Well... both are kind of far from the original style... but norm 1 is closer...

**Comment by bmaltais** [comment] 2023-07-01 14:28
> @bmaltais cool so I think I can close this issue?

Yes, appear to be solved

**Closed** 2023-07-01 15:20 UTC
