### ISSUE TITLE
LoHa loss shoot through the roof

### ISSUE THREAD

**Issue by bmaltais** [KohakuBlueleaf/LyCORIS#15] opened 2023-03-09 12:47 UTC
I have been trainina using the new LoHa tytpe and the Loss went through the roof... but using the previous LoCon method is working fine:

![image](https://user-images.githubusercontent.com/7474674/224027147-3b200aba-575a-465f-9e7f-e93523452cfb.png)

Command used for LoHa. LoCon was same except for using `algo=lora`:

`accelerate launch --num_cpu_threads_per_process=2 "train_network.py" --enable_bucket --pretrained_model_name_or_path="D:/models/v1-5-pruned.ckpt" --train_data_dir="D:\dataset\trailbugprints\img_g8" --resolution=512,512 --output_dir="D:/lora/sd1.5/trailbugprints" --logging_dir="D:\dataset\trailbugprints\lora\logs" --network_alpha="384" --save_model_as=safetensors --network_module=lycoris.kohya --network_args "conv_dim=384" "conv_alpha=384" "algo=loha" --text_encoder_lr=0.00005 --unet_lr=0.0001 --network_dim=384 --output_name="trailbugprints_v1.0c" --lr_scheduler_num_cycles="4" --learning_rate="0.0001" --lr_scheduler="constant" --train_batch_size="8" --max_train_steps="600" --save_every_n_epochs="1" --mixed_precision="bf16" --save_precision="fp16" --caption_extension=".txt" --cache_latents --optimizer_type="AdamW8bit" --max_data_loader_n_workers="0" --caption_dropout_rate="0.05" --bucket_reso_steps=1 --xformers --bucket_no_upscale --noise_offset=0.05  --sample_sampler=dpmsolver++ --sample_prompts="D:/lora/sd1.5/trailbugprints\sample\prompt.txt" --sample_every_n_steps="100"`

**Comment by KohakuBlueleaf** [comment] 2023-03-09 13:13
your dim is way too high,
you are not supposed to use dim > sqrt(original dim) in loha.

I will add a warning message on it...

**Comment by KohakuBlueleaf** [comment] 2023-03-09 13:16
@bmaltais or you can use lower lr for super high dim loha,
this is not a bug, and actually normal(.

**Comment by KohakuBlueleaf** [comment] 2023-03-09 13:27
@bmaltais Or you can fix on alpha=1, this may help you.

**Comment by bmaltais** [comment] 2023-03-09 14:50
Thank you. I have been creating LoRA with the highest possible ranks thinking I would extract more from the dataset. I then do a sv_fro resize of the large LoRA to reduce it down to a smaller size (usually 92% reductio) without loosing much from the original model. I guess with LoHa I will need a different approach...

What would you say is a practical upper limit for rank and alpha? When doing LoRA I use 512 rank and 512 alpha... when doing LoCon I used 384 for all of them because otherwise I get OOM error.

Any recommendations?

**Comment by KohakuBlueleaf** [comment] 2023-03-09 14:56
@bmaltais LoHA is not working like conventional LoRA, you can not use any way to "resize" a LoHa, (or you want to merge it and then extract to LoCon?)
And for what you want to do, you should use dreambooth to train whole model and then extract.

BTW, the rank of LoHa is dim**2, which means you only need dim=64 to get 4096 rank.

**Comment by KohakuBlueleaf** [comment] 2023-03-09 15:07
@bmaltais  and for my own opinion, if you want to use any dim>128, you should use dreambooth and then extract. not just train a lora on it. different layer need different rank.

And use frobinous norm is not good to me BTW, I will use quantile/percentile of singular value to dynamic extract the  lora/locon.

**Comment by bmaltais** [comment] 2023-03-09 15:10
@KohakuBlueleaf Interesting. I have not had great results in the past extracting from dreambooth models. LoRA trained with high rank produced much better results vs dreambooth extraction... But perhaps I should try it again.

**Comment by bmaltais** [comment] 2023-03-09 15:13
I see your extraction tool is much different from kohya... perhaps my issue with extraction is the tool I use ;-) Do you have a recommendation for configuration when using your extract.py tool to extract from a dreambooth checkpoint?

**Comment by KohakuBlueleaf** [comment] 2023-03-09 15:14
@bmaltais You can refer this:
https://huggingface.co/alea31415/umamusume-full/tree/main/extracted_locons

**Comment by KohakuBlueleaf** [comment] 2023-03-09 15:15
@bmaltais basically start at 0.75/0.75 quantile for both linear and conv
and then reduce them until you are not like the result

**Comment by bmaltais** [comment] 2023-03-09 15:39
@KohakuBlueleaf Tried running:

`python tools\lycoris_locon_extract.py --mode quantile --safetensors --linear_quantile 0.75 --conv_quantile 0.75 --device cuda D:/models/v1-5-pruned.ckpt D:/models/cyberrealistic_v12.safetensors "D:/lora/sd1.5/cyberrealistic_v12.safetensors"`

But I get:

```
  File "D:\kohya_ss\venv\lib\site-packages\lycoris\utils.py", line 96, in extract_linear
    lora_rank = max(1, lora_rank)
UnboundLocalError: local variable 'lora_rank' referenced before assignment
```

Is it possible the utils.py need a variable allocated earlier on?

**Comment by KohakuBlueleaf** [comment] 2023-03-09 16:20
This is because your lycoris_lora is on old version
I have push some fix for this
Include: fix sys.path for tools scripts
Add NotImpl error for this kind of situation

Plz make sure you are at the latest commit and latest version of the package

**Comment by bmaltais** [comment] 2023-03-09 16:44
OK, I was pinned at 0.0.5. Now up to 0.0.9. Will give it another try. Thanks!

I am trying a LoHa at dim/alpha of 8 for Linear and Conv... will see how it goes. So far so good. Trying to update the GUI to support the new LoHa.

**Comment by KohakuBlueleaf** [comment] 2023-03-09 17:19
@bmaltais if you need further help for this project or track the new thing, you can consider join this dc.
https://discord.gg/6VEnAtSC87

Or contact me in the SAIL or 東方AI server

**Closed by KohakuBlueleaf** 2023-03-09 17:19 UTC
